### ISSUE TITLE
Updates for Python3

### ISSUE THREAD

**Issue by cjnolet** [jerkern/pyParticleEst#3]
When attempting to import this library for Python3.5, I get the infamous "No module named 'exceptions'" error.

It really would be useful to see this library updated for Python3.

**Comment by jerkern** [comment]
Hi

Thanks for filling an issue! I haven't used the library myself in some time since my daily work these days don't include these type of estimations, otherwise I would have surely ported it already.

So this is definitely on my to fix list, but I'm swamped at the moment, so don't know when I'll get the time.

In them meantime, if you, or someone else, wants to make a patch I'd be happy to help out with any issues you run into.

**Comment by MAbdelatti** [comment]
Hi,
The library works well on Python 2.7. However, when I use Python 3.6, I get this message:

/usr/bin/python3 "some directories..."/particle_filter.py
Traceback (most recent call last):
  File ""some directories..."/particle_filter.py", line 9, in <module>
    import pyparticleest.simulator as simulator
  File ""some directories..."/.local/lib/python3.6/site-packages/pyparticleest/simulator.py", line 9, in <module>
    from filter import ParticleTrajectory
ModuleNotFoundError: No module named 'filter

**Comment by jerkern** [comment]
There is an active pull request #4 that I will try to review and merge as soon a possible, hopefully that will solve the python3 issues.

**Comment by jerkern** [comment]
Fixed in 1.1.4

**Comment by MAbdelatti** [comment]
Thank you very much.
